package com.rdr.cecdoc.model;


public enum ChampDossier {
    PRENOMS_ETAT_CIVIL, PRENOMS_USAGE, NOM_FAMILLE, DATE_NAISSANCE, LIEU_NAISSANCE, SEXE_ETAT_CIVIL, ADRESSE, VILLE_ACTUELLE, TRIBUNAL, RECIT, NATIONALITE, PROFESSION, SITUATION_MATRIMONIALE, SITUATION_ENFANTS
}
